// packages/solid/src/Select.tsx
import { createEffect, createSignal, onCleanup, onMount, on, type JSX } from 'solid-js'
import { render } from 'solid-js/web'
import type {
  SelectEventDetail,
  SearchEventDetail,
  ChangeEventDetail,
  LoadMoreEventDetail,
  ClearEventDetail,
  GroupedItem,
  ClassMap,
  RendererHelpers,
  DiagnosticEventDetail,
  LimitationPolicyMap,
  TrackingSnapshot,
  SelectCapabilitiesReport,
  LimitationState,
  GlobalSelectConfig,
  SelectionConfig,
  MultiSelectDisplayConfig,
  ScrollToSelectedConfig,
  StyleConfig,
} from '@smilodon/core'

export interface SelectItem {
  value: string | number
  label: string
  disabled?: boolean
  group?: string
  [key: string]: unknown
}

type SelectValue = string | number | Array<string | number>

type EnhancedSelectElement = HTMLElement & {
  setItems?: (items: SelectItem[]) => void
  setGroupedItems?: (groups: GroupedItem[]) => void
  getSelectedItems?: () => SelectItem[]
  getSelectedValues?: () => Array<string | number>
  setSelectedValues?: (values: Array<string | number>) => void
  updateConfig?: (config: unknown) => void
  open?: () => void
  close?: () => void
  clearSearch?: () => void
  setError?: (message: string) => void
  clearError?: () => void
  setRequired?: (required: boolean) => void
  validate?: () => boolean
  optionRenderer?: ((item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement) | undefined
  groupHeaderRenderer?: ((group: GroupedItem, index: number) => HTMLElement) | undefined
  classMap?: ClassMap | undefined
  getCapabilities?: () => SelectCapabilitiesReport
  getKnownLimitations?: () => LimitationState[]
  getTrackingSnapshot?: () => TrackingSnapshot
  clearTracking?: (source?: 'event' | 'style' | 'limitation' | 'all') => void
  setLimitationPolicies?: (policies: LimitationPolicyMap) => void
}

export interface SelectHandle {
  focus: () => void
  open: () => void
  close: () => void
  getSelectedItems: () => SelectItem[]
  getSelectedValues: () => Array<string | number>
  setItems: (items: SelectItem[]) => void
  setGroupedItems: (groups: GroupedItem[]) => void
  clear: () => void
  clearSearch: () => void
  updateConfig: (config: Partial<GlobalSelectConfig>) => void
  setError: (message: string) => void
  clearError: () => void
  setRequired: (required: boolean) => void
  validate: () => boolean
  getCapabilities: () => SelectCapabilitiesReport | undefined
  getKnownLimitations: () => LimitationState[]
  getTrackingSnapshot: () => TrackingSnapshot
  clearTracking: (source?: 'event' | 'style' | 'limitation' | 'all') => void
  setLimitationPolicies: (policies: LimitationPolicyMap) => void
}

export interface SelectProps {
  items?: SelectItem[]
  groupedItems?: GroupedItem[]
  groupHeaderRenderer?: (group: GroupedItem, index: number) => JSX.Element
  value?: SelectValue
  defaultValue?: SelectValue
  multiple?: boolean
  searchable?: boolean
  placeholder?: string
  disabled?: boolean
  required?: boolean
  error?: boolean
  infiniteScroll?: boolean
  pageSize?: number
  virtualized?: boolean
  maxSelections?: number
  selectionConfig?: Partial<SelectionConfig>
  multiSelectDisplay?: Partial<MultiSelectDisplayConfig>
  scrollToSelected?: Partial<ScrollToSelectedConfig>
  styles?: StyleConfig
  config?: Partial<GlobalSelectConfig>
  removeButtonIcon?: string
  disabledOptionBehavior?: {
    selectable?: boolean
    hoverable?: boolean
    focusable?: boolean
  }
  showSelectedIndicator?: boolean
  direction?: 'ltr' | 'rtl'
  placement?: 'bottom' | 'top' | 'auto'
  class?: string
  className?: string
  style?: JSX.CSSProperties
  expandable?: boolean
  clearable?: boolean
  clearSelectionOnClear?: boolean
  clearSearchOnClear?: boolean
  clearAriaLabel?: string
  clearIcon?: string
  classMap?: ClassMap
  optionRenderer?: (item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement
  customRenderer?: (item: SelectItem, index: number) => JSX.Element
  trackingEnabled?: boolean
  trackEvents?: boolean
  trackStyling?: boolean
  trackLimitations?: boolean
  emitDiagnostics?: boolean
  trackingMaxEntries?: number
  limitationPolicies?: LimitationPolicyMap
  autoMitigateRuntimeModeSwitch?: boolean
  onChange?: (value: SelectValue, items: SelectItem[]) => void
  onSelect?: (item: SelectItem, index: number) => void
  onOpen?: () => void
  onClose?: () => void
  onSearch?: (query: string) => void
  onLoadMore?: (page: number) => void
  onCreate?: (value: string) => void
  onClear?: (detail: { clearedSelection: boolean; clearedSearch: boolean }) => void
  onDiagnostic?: (detail: DiagnosticEventDetail) => void
  ref?: (handle: SelectHandle) => void
}

const defaultProps = {
  items: () => [] as SelectItem[],
  multiple: false,
  searchable: false,
  disabled: false,
  required: false,
  error: false,
  infiniteScroll: false,
  pageSize: 50,
  virtualized: true,
  showSelectedIndicator: true,
  placement: 'auto' as const,
  clearable: false,
  clearSelectionOnClear: true,
  clearSearchOnClear: true,
  trackingEnabled: false,
  trackEvents: true,
  trackStyling: true,
  trackLimitations: true,
  emitDiagnostics: false,
  trackingMaxEntries: 200,
  autoMitigateRuntimeModeSwitch: true,
}

export default function Select(rawProps: SelectProps) {
  const props = {
    ...defaultProps,
    ...rawProps,
    items: rawProps.items ?? defaultProps.items(),
  }

  let selectRef: EnhancedSelectElement | undefined
  const [isElementReady, setIsElementReady] = createSignal(false)
  const [internalValue, setInternalValue] = createSignal<SelectValue | undefined>(props.defaultValue)
  const [resolvedOptionRenderer, setResolvedOptionRenderer] = createSignal<SelectProps['optionRenderer'] | ((item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement) | undefined>()
  const customRendererCache = new Map<number, { container: HTMLDivElement; dispose?: () => void }>()
  const groupHeaderDisposers = new Set<() => void>()

  const isControlled = () => rawProps.value !== undefined
  const currentValue = () => (isControlled() ? rawProps.value : internalValue())

  const toArrayValue = (value: SelectValue | undefined) =>
    value === undefined ? [] : Array.isArray(value) ? value : [value]

  const resolvePlacementMode = () => {
    const placement = rawProps.placement ?? props.placement
    return placement === 'auto' ? 'auto' : placement === 'top' ? 'top' : 'bottom'
  }

  const cleanupCustomRendererCache = () => {
    for (const entry of customRendererCache.values()) {
      entry.dispose?.()
      entry.container.remove()
    }
    customRendererCache.clear()
  }

  const cleanupGroupHeaderRenderers = () => {
    for (const dispose of groupHeaderDisposers) dispose()
    groupHeaderDisposers.clear()
  }

  const safeCall = (fn: (el: EnhancedSelectElement) => void) => {
    if (!selectRef || !isElementReady()) return
    fn(selectRef)
  }

  const syncItems = (el: EnhancedSelectElement) => {
    if (rawProps.groupedItems?.length) {
      el.setGroupedItems?.(rawProps.groupedItems)
      return
    }

    if (!rawProps.items?.length) {
      el.setItems?.([])
      return
    }

    const first = rawProps.items[0]
    if (first && first.group !== undefined) {
      const grouped = Array.from(
        rawProps.items.reduce((map, item) => {
          const groupName = item.group ?? 'Ungrouped'
          const group = map.get(groupName)
          if (group) {
            group.options.push(item)
          } else {
            map.set(groupName, { label: groupName, options: [item] })
          }
          return map
        }, new Map<string, GroupedItem>()).values()
      )
      el.setGroupedItems?.(grouped)
      return
    }

    el.setItems?.(rawProps.items)
  }

  createEffect(
    on(
      [() => !!rawProps.optionRenderer, () => !!rawProps.customRenderer],
      ([hasOptionRenderer, hasCustomRenderer]: [boolean, boolean]) => {
        if (hasOptionRenderer) {
          setResolvedOptionRenderer(() => (item: SelectItem, index: number, helpers?: RendererHelpers) =>
            rawProps.optionRenderer?.(item, index, helpers as RendererHelpers) ?? document.createElement('div')
          )
          return
        }

        if (hasCustomRenderer) {
          setResolvedOptionRenderer(() => (item: SelectItem, index: number) => {
            let entry = customRendererCache.get(index)
            if (!entry) {
              entry = { container: document.createElement('div') }
              customRendererCache.set(index, entry)
            }

            entry.dispose?.()
            entry.dispose = render(() => rawProps.customRenderer?.(item, index) ?? null, entry.container)
            return entry.container
          })
          return
        }

        cleanupCustomRendererCache()
        setResolvedOptionRenderer(undefined)
      },
      { defer: false }
    )
  )

  createEffect(() => {
    const ready = isElementReady()
    const renderer = resolvedOptionRenderer()
    if (!ready) return
    safeCall((el) => {
      el.optionRenderer = renderer
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    const classMap = rawProps.classMap
    if (!ready) return

    safeCall((el) => {
      el.classMap = classMap
    })
  })

  createEffect(() => {
    const items = rawProps.items
    const groups = rawProps.groupedItems
    const totalItems = groups?.length
      ? groups.reduce((count, group) => count + group.options.length, 0)
      : items?.length ?? 0

    for (const [index, entry] of customRendererCache.entries()) {
      if (index >= totalItems) {
        entry.dispose?.()
        entry.container.remove()
        customRendererCache.delete(index)
      }
    }
  })

  createEffect(() => {
    if (!isElementReady()) return
    safeCall((el) => syncItems(el))
  })

  createEffect(() => {
    const ready = isElementReady()
    const renderer = rawProps.groupHeaderRenderer
    if (!ready) return

    safeCall((el) => {
      cleanupGroupHeaderRenderers()
      if (!renderer) {
        el.groupHeaderRenderer = undefined
        return
      }

      el.groupHeaderRenderer = (group: GroupedItem, index: number) => {
        const container = document.createElement('div')
        const dispose = render(() => renderer(group, index), container)
        groupHeaderDisposers.add(dispose)
        return container
      }
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    const placement = rawProps.placement ?? props.placement
    if (!ready || !selectRef) return
    if (placement) {
      selectRef.setAttribute('placement', placement)
    }
  })

  createEffect(() => {
    const ready = isElementReady()
    const value = currentValue()
    if (!ready || value === undefined) return

    safeCall((el) => {
      const currentSelected = el.getSelectedValues?.() ?? []
      const nextValues = toArrayValue(value)
      const hasChanged =
        currentSelected.length !== nextValues.length ||
        !currentSelected.every((selectedValue, index) => selectedValue === nextValues[index])

      if (hasChanged) {
        el.setSelectedValues?.(nextValues)
      }
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    if (!ready) return

    safeCall((el) => {
      el.updateConfig?.({
        searchable: rawProps.searchable ?? props.searchable,
        placeholder: rawProps.placeholder,
        enabled: !(rawProps.disabled ?? props.disabled),
        virtualize: rawProps.virtualized ?? props.virtualized,
        dropdownPlacement: {
          mode: resolvePlacementMode(),
        },
        direction: rawProps.direction,
        selection: {
          ...(rawProps.selectionConfig ?? {}),
          mode: (rawProps.multiple ?? props.multiple) ? 'multi' : 'single',
          maxSelections: rawProps.maxSelections,
          removeButtonIcon: rawProps.removeButtonIcon,
            disabledOptionBehavior: rawProps.disabledOptionBehavior,
            showSelectedIndicator: rawProps.showSelectedIndicator ?? props.showSelectedIndicator,
        },
        multiSelectDisplay: rawProps.multiSelectDisplay,
        infiniteScroll: {
          enabled: rawProps.infiniteScroll ?? props.infiniteScroll,
          pageSize: rawProps.pageSize ?? props.pageSize,
        },
        scrollToSelected: {
          enabled: true,
          ...(rawProps.scrollToSelected ?? {}),
        },
        styles: rawProps.styles,
        expandable: {
          enabled: rawProps.expandable,
        },
        clearControl: {
          enabled: rawProps.clearable ?? props.clearable,
          clearSelection: rawProps.clearSelectionOnClear ?? props.clearSelectionOnClear,
          clearSearch: rawProps.clearSearchOnClear ?? props.clearSearchOnClear,
          ariaLabel: rawProps.clearAriaLabel,
          icon: rawProps.clearIcon,
        },
        tracking: {
          enabled: rawProps.trackingEnabled ?? props.trackingEnabled,
          events: rawProps.trackEvents ?? props.trackEvents,
          styling: rawProps.trackStyling ?? props.trackStyling,
          limitations: rawProps.trackLimitations ?? props.trackLimitations,
          emitDiagnostics: rawProps.emitDiagnostics ?? props.emitDiagnostics,
          maxEntries: rawProps.trackingMaxEntries ?? props.trackingMaxEntries,
        },
        limitations: {
          policies: rawProps.limitationPolicies,
          autoMitigateRuntimeModeSwitch:
            rawProps.autoMitigateRuntimeModeSwitch ?? props.autoMitigateRuntimeModeSwitch,
        },
      })
      if (rawProps.config) {
        el.updateConfig?.(rawProps.config)
      }
    })
  })

  const waitForUpgrade = async () => {
    if (typeof window === 'undefined') return

    if (!customElements.get('enhanced-select')) {
      await import('@smilodon/core')
    }

    if (!selectRef) return

    try {
      await customElements.whenDefined('enhanced-select')
    } catch {
      // ignore
    }

    for (let index = 0; index < 5; index += 1) {
      if (selectRef && typeof selectRef.setItems === 'function') {
        setIsElementReady(true)
        if (resolvedOptionRenderer()) {
          selectRef.optionRenderer = resolvedOptionRenderer()
        }
        if (rawProps.classMap) {
          selectRef.classMap = rawProps.classMap
        }
        return
      }
      await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()))
    }

    setIsElementReady(Boolean(selectRef && typeof selectRef.setItems === 'function'))
    if (selectRef && resolvedOptionRenderer()) {
      selectRef.optionRenderer = resolvedOptionRenderer()
    }
    if (selectRef && rawProps.classMap) {
      selectRef.classMap = rawProps.classMap
    }
  }

  const handleSelect = (event: Event) => {
    const customEvent = event as CustomEvent<SelectEventDetail>
    rawProps.onSelect?.(customEvent.detail.item as SelectItem, customEvent.detail.index)
  }

  const handleChange = (event: Event) => {
    const customEvent = event as CustomEvent<ChangeEventDetail>
    const values = customEvent.detail.selectedValues as Array<string | number>
    const nextValue = (rawProps.multiple ?? props.multiple) ? values : values[0] ?? ''

    if (!isControlled()) {
      setInternalValue(nextValue)
    }

    rawProps.onChange?.(nextValue, customEvent.detail.selectedItems as SelectItem[])
  }

  const handleSearch = (event: Event) => {
    const customEvent = event as CustomEvent<SearchEventDetail>
    rawProps.onSearch?.(customEvent.detail.query)
  }

  const handleLoadMore = (event: Event) => {
    const customEvent = event as CustomEvent<LoadMoreEventDetail>
    rawProps.onLoadMore?.(customEvent.detail.page)
  }

  const handleCreate = (event: Event) => {
    const customEvent = event as CustomEvent<{ value: string }>
    rawProps.onCreate?.(customEvent.detail.value)
  }

  const handleClear = (event: Event) => {
    const customEvent = event as CustomEvent<ClearEventDetail>
    rawProps.onClear?.({
      clearedSelection: customEvent.detail.clearedSelection,
      clearedSearch: customEvent.detail.clearedSearch,
    })
  }

  const handleDiagnostic = (event: Event) => {
    const customEvent = event as CustomEvent<DiagnosticEventDetail>
    rawProps.onDiagnostic?.(customEvent.detail)
  }

  const handleOpen = () => rawProps.onOpen?.()
  const handleClose = () => rawProps.onClose?.()

  const handle: SelectHandle = {
    focus: () => selectRef?.focus(),
    open: () => selectRef?.open?.(),
    close: () => selectRef?.close?.(),
    getSelectedItems: () => selectRef?.getSelectedItems?.() ?? [],
    getSelectedValues: () => selectRef?.getSelectedValues?.() ?? [],
    setItems: (items) => selectRef?.setItems?.(items),
    setGroupedItems: (groups) => selectRef?.setGroupedItems?.(groups),
    clear: () => {
      selectRef?.setSelectedValues?.([])
      if (!isControlled()) {
        setInternalValue((rawProps.multiple ?? props.multiple) ? [] : '')
      }
      rawProps.onChange?.((rawProps.multiple ?? props.multiple) ? [] : '', [])
    },
    clearSearch: () => selectRef?.clearSearch?.(),
    updateConfig: (config) => selectRef?.updateConfig?.(config),
    setError: (message) => selectRef?.setError?.(message),
    clearError: () => selectRef?.clearError?.(),
    setRequired: (required) => selectRef?.setRequired?.(required),
    validate: () => selectRef?.validate?.() ?? true,
    getCapabilities: () => selectRef?.getCapabilities?.(),
    getKnownLimitations: () => selectRef?.getKnownLimitations?.() ?? [],
    getTrackingSnapshot: () => selectRef?.getTrackingSnapshot?.() ?? { events: [], styles: [], limitations: [] },
    clearTracking: (source) => selectRef?.clearTracking?.(source),
    setLimitationPolicies: (policies) => selectRef?.setLimitationPolicies?.(policies),
  }

  onMount(async () => {
    await waitForUpgrade()
    if (!selectRef || !isElementReady()) return

    props.ref?.(handle)

    syncItems(selectRef)

    const initialValues = toArrayValue(currentValue())
    if (initialValues.length) {
      selectRef.setSelectedValues?.(initialValues)
    }

    selectRef.addEventListener('select', handleSelect as EventListener)
    selectRef.addEventListener('change', handleChange as EventListener)
    selectRef.addEventListener('open', handleOpen as EventListener)
    selectRef.addEventListener('close', handleClose as EventListener)
    selectRef.addEventListener('search', handleSearch as EventListener)
    selectRef.addEventListener('loadMore', handleLoadMore as EventListener)
    selectRef.addEventListener('create', handleCreate as EventListener)
    selectRef.addEventListener('clear', handleClear as EventListener)
    selectRef.addEventListener('diagnostic', handleDiagnostic as EventListener)
  })

  onCleanup(() => {
    cleanupCustomRendererCache()
    cleanupGroupHeaderRenderers()

    if (!selectRef) return

    selectRef.removeEventListener('select', handleSelect as EventListener)
    selectRef.removeEventListener('change', handleChange as EventListener)
    selectRef.removeEventListener('open', handleOpen as EventListener)
    selectRef.removeEventListener('close', handleClose as EventListener)
    selectRef.removeEventListener('search', handleSearch as EventListener)
    selectRef.removeEventListener('loadMore', handleLoadMore as EventListener)
    selectRef.removeEventListener('create', handleCreate as EventListener)
    selectRef.removeEventListener('clear', handleClear as EventListener)
    selectRef.removeEventListener('diagnostic', handleDiagnostic as EventListener)
  })

  return (
    <enhanced-select
      ref={(element: Element) => {
        selectRef = element as EnhancedSelectElement
      }}
      class={rawProps.class ?? rawProps.className}
      style={rawProps.style as JSX.CSSProperties}
        dir={rawProps.direction}
    />
  )
}

// packages/react-native/src/Select.tsx
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'
import {
  StyleSheet,
  View,
  type StyleProp,
  type ViewStyle,
} from 'react-native'
import { WebView, type WebViewMessageEvent } from 'react-native-webview'
import coreBundle from './generated/coreBundle.js'
import type {
  GlobalSelectConfig,
  SelectionConfig,
  MultiSelectDisplayConfig,
  ScrollToSelectedConfig,
  StyleConfig,
} from '@smilodon/core'

export interface SelectItem {
  value: string | number
  label: string
  disabled?: boolean
  group?: string
  [key: string]: unknown
}

export interface GroupedItem {
  label: string
  options: SelectItem[]
}

export interface DiagnosticEventDetail {
  channel: string
  message: string
  [key: string]: unknown
}

export interface LimitationPolicyMap {
  [key: string]: unknown
}

export interface TrackingSnapshot {
  events: unknown[]
  styles: unknown[]
  limitations: unknown[]
}

export interface SelectCapabilitiesReport {
  [key: string]: unknown
}

export interface LimitationState {
  [key: string]: unknown
}

export type SelectValue = string | number | Array<string | number>

export interface SelectHandle {
  open: () => void
  close: () => void
  clear: () => void
  clearSearch: () => void
  setItems: (items: SelectItem[]) => void
  setGroupedItems: (groups: GroupedItem[]) => void
  setValue: (value: SelectValue | undefined) => void
  updateConfig: (config: Partial<GlobalSelectConfig>) => void
}

export interface SelectProps {
  items?: SelectItem[]
  groupedItems?: GroupedItem[]
  value?: SelectValue
  defaultValue?: SelectValue
  multiple?: boolean
  searchable?: boolean
  placeholder?: string
  disabled?: boolean
  infiniteScroll?: boolean
  pageSize?: number
  virtualized?: boolean
  maxSelections?: number
  selectionConfig?: Partial<SelectionConfig>
  multiSelectDisplay?: Partial<MultiSelectDisplayConfig>
  scrollToSelected?: Partial<ScrollToSelectedConfig>
  styles?: StyleConfig
  config?: Partial<GlobalSelectConfig>
  removeButtonIcon?: string
  disabledOptionBehavior?: {
    selectable?: boolean
    hoverable?: boolean
    focusable?: boolean
  }
  showSelectedIndicator?: boolean
  direction?: 'ltr' | 'rtl'
  clearable?: boolean
  clearSelectionOnClear?: boolean
  clearSearchOnClear?: boolean
  clearAriaLabel?: string
  clearIcon?: string
  expandable?: boolean
  trackingEnabled?: boolean
  trackEvents?: boolean
  trackStyling?: boolean
  trackLimitations?: boolean
  emitDiagnostics?: boolean
  trackingMaxEntries?: number
  limitationPolicies?: LimitationPolicyMap
  autoMitigateRuntimeModeSwitch?: boolean
  containerStyle?: StyleProp<ViewStyle>
  selectStyle?: Record<string, string>
  collapsedHeight?: number
  expandedHeight?: number
  onChange?: (value: SelectValue, items: SelectItem[]) => void
  onSelect?: (item: SelectItem, index: number) => void
  onOpen?: () => void
  onClose?: () => void
  onSearch?: (query: string) => void
  onLoadMore?: (page: number) => void
  onCreate?: (value: string) => void
  onClear?: (detail: { clearedSelection: boolean; clearedSearch: boolean }) => void
  onDiagnostic?: (detail: DiagnosticEventDetail) => void
}

type BridgePayload = {
  items?: SelectItem[]
  groupedItems?: GroupedItem[]
  value?: Array<string | number>
  config: Record<string, unknown>
  selectStyle?: Record<string, string>
}

const DEFAULT_COLLAPSED_HEIGHT = 64
const DEFAULT_EXPANDED_HEIGHT = 360

function toArrayValue(value: SelectValue | undefined): Array<string | number> {
  if (value === undefined) return []
  return Array.isArray(value) ? value : [value]
}

function escapeForInjection(value: unknown) {
  return JSON.stringify(value)
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\\$')
}

function createHtml(collapsedHeight: number) {
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        background: transparent;
        overflow: hidden;
        height: ${collapsedHeight}px;
      }

      #root {
        min-height: ${collapsedHeight}px;
        padding: 0;
      }

      enhanced-select {
        display: block;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="root">
      <enhanced-select id="smilodon-select"></enhanced-select>
    </div>
    <script>${coreBundle}</script>
    <script>
      (function () {
        const root = document.getElementById('root');
        const el = document.getElementById('smilodon-select');

        function post(message) {
          if (window.ReactNativeWebView) {
            window.ReactNativeWebView.postMessage(JSON.stringify(message));
          }
        }

        function setHeight(height) {
          document.documentElement.style.height = height + 'px';
          document.body.style.height = height + 'px';
          root.style.minHeight = height + 'px';
          post({ type: 'height', value: height });
        }

        function applyPayload(payload) {
          if (!payload) return;

          if (payload.selectStyle) {
            Object.entries(payload.selectStyle).forEach(([key, value]) => {
              el.style.setProperty(key, String(value));
            });
          }

          if (payload.groupedItems && payload.groupedItems.length) {
            el.setGroupedItems(payload.groupedItems);
          } else if (payload.items) {
            el.setItems(payload.items);
          }

          if (payload.value) {
            el.setSelectedValues(payload.value);
          } else {
            el.setSelectedValues([]);
          }

          el.updateConfig(payload.config || {});
        }

        window.__smilodonNativeBridge = {
          sync(payload) {
            applyPayload(payload);
          },
          open() {
            el.open();
          },
          close() {
            el.close();
          },
          clear() {
            el.setSelectedValues([]);
          },
          clearSearch() {
            el.clearSearch && el.clearSearch();
          }
        };

        el.addEventListener('select', function (event) {
          post({ type: 'select', detail: event.detail });
        });

        el.addEventListener('change', function (event) {
          post({ type: 'change', detail: event.detail });
        });

        el.addEventListener('open', function () {
          setHeight(window.__smilodonExpandedHeight || ${DEFAULT_EXPANDED_HEIGHT});
          post({ type: 'open' });
        });

        el.addEventListener('close', function () {
          setHeight(window.__smilodonCollapsedHeight || ${DEFAULT_COLLAPSED_HEIGHT});
          post({ type: 'close' });
        });

        el.addEventListener('search', function (event) {
          post({ type: 'search', detail: event.detail });
        });

        el.addEventListener('loadMore', function (event) {
          post({ type: 'loadMore', detail: event.detail });
        });

        el.addEventListener('create', function (event) {
          post({ type: 'create', detail: event.detail });
        });

        el.addEventListener('clear', function (event) {
          post({ type: 'clear', detail: event.detail });
        });

        el.addEventListener('diagnostic', function (event) {
          post({ type: 'diagnostic', detail: event.detail });
        });

        Promise.resolve(customElements.whenDefined('enhanced-select')).then(function () {
          setHeight(window.__smilodonCollapsedHeight || ${DEFAULT_COLLAPSED_HEIGHT});
          post({ type: 'ready' });
        });
      })();
    </script>
  </body>
</html>`
}

const Select = forwardRef<SelectHandle, SelectProps>(function Select(
  {
    items,
    groupedItems,
    value,
    defaultValue,
    multiple = false,
    searchable = false,
    placeholder,
    disabled = false,
    infiniteScroll = false,
    pageSize = 50,
    virtualized = true,
    maxSelections,
    selectionConfig,
    multiSelectDisplay,
    scrollToSelected,
    styles: stylesConfig,
    config: coreConfig,
    removeButtonIcon,
    disabledOptionBehavior,
    showSelectedIndicator = true,
    direction,
    clearable = false,
    clearSelectionOnClear = true,
    clearSearchOnClear = true,
    clearAriaLabel,
    clearIcon,
    expandable,
    trackingEnabled = false,
    trackEvents = true,
    trackStyling = true,
    trackLimitations = true,
    emitDiagnostics = false,
    trackingMaxEntries = 200,
    limitationPolicies,
    autoMitigateRuntimeModeSwitch = true,
    containerStyle,
    selectStyle,
    collapsedHeight = DEFAULT_COLLAPSED_HEIGHT,
    expandedHeight = DEFAULT_EXPANDED_HEIGHT,
    onChange,
    onSelect,
    onOpen,
    onClose,
    onSearch,
    onLoadMore,
    onCreate,
    onClear,
    onDiagnostic,
  },
  ref
) {
  const webViewRef = useRef<WebView>(null)
  const [isReady, setIsReady] = useState(false)
  const [webViewHeight, setWebViewHeight] = useState(collapsedHeight)
  const [internalValue, setInternalValue] = useState<SelectValue | undefined>(defaultValue)

  const currentValue = value !== undefined ? value : internalValue

  const bridgePayload = useMemo<BridgePayload>(() => ({
    items,
    groupedItems,
    value: toArrayValue(currentValue),
    selectStyle,
    config: {
      searchable,
      placeholder,
      enabled: !disabled,
      virtualize: virtualized,
      direction,
      dropdownPlacement: {
        mode: 'auto',
      },
      selection: {
        ...(selectionConfig ?? {}),
        mode: multiple ? 'multi' : 'single',
        maxSelections,
        removeButtonIcon,
        disabledOptionBehavior,
        showSelectedIndicator,
      },
      multiSelectDisplay,
      infiniteScroll: {
        enabled: infiniteScroll,
        pageSize,
      },
      scrollToSelected: {
        enabled: true,
        ...(scrollToSelected ?? {}),
      },
      styles: stylesConfig,
      expandable: {
        enabled: expandable,
      },
      clearControl: {
        enabled: clearable,
        clearSelection: clearSelectionOnClear,
        clearSearch: clearSearchOnClear,
        ariaLabel: clearAriaLabel,
        icon: clearIcon,
      },
      tracking: {
        enabled: trackingEnabled,
        events: trackEvents,
        styling: trackStyling,
        limitations: trackLimitations,
        emitDiagnostics,
        maxEntries: trackingMaxEntries,
      },
      limitations: {
        policies: limitationPolicies,
        autoMitigateRuntimeModeSwitch,
      },
      ...(coreConfig ?? {}),
    },
  }), [
    items,
    groupedItems,
    currentValue,
    selectStyle,
    searchable,
    placeholder,
    disabled,
    virtualized,
    selectionConfig,
    multiSelectDisplay,
    scrollToSelected,
    stylesConfig,
    coreConfig,
    multiple,
    maxSelections,
    removeButtonIcon,
    disabledOptionBehavior,
    showSelectedIndicator,
    direction,
    infiniteScroll,
    pageSize,
    expandable,
    clearable,
    clearSelectionOnClear,
    clearSearchOnClear,
    clearAriaLabel,
    clearIcon,
    trackingEnabled,
    trackEvents,
    trackStyling,
    trackLimitations,
    emitDiagnostics,
    trackingMaxEntries,
    limitationPolicies,
    autoMitigateRuntimeModeSwitch,
  ])

  const syncToWebView = useCallback((payload: BridgePayload) => {
    const js = `
      window.__smilodonCollapsedHeight = ${collapsedHeight};
      window.__smilodonExpandedHeight = ${expandedHeight};
      window.__smilodonNativeBridge && window.__smilodonNativeBridge.sync(${escapeForInjection(payload)});
      true;
    `
    webViewRef.current?.injectJavaScript(js)
  }, [collapsedHeight, expandedHeight])

  useEffect(() => {
    if (!isReady) return
    syncToWebView(bridgePayload)
  }, [bridgePayload, isReady, syncToWebView])

  useImperativeHandle(ref, () => ({
    open: () => {
      webViewRef.current?.injectJavaScript('window.__smilodonNativeBridge && window.__smilodonNativeBridge.open(); true;')
    },
    close: () => {
      webViewRef.current?.injectJavaScript('window.__smilodonNativeBridge && window.__smilodonNativeBridge.close(); true;')
    },
    clear: () => {
      webViewRef.current?.injectJavaScript('window.__smilodonNativeBridge && window.__smilodonNativeBridge.clear(); true;')
    },
    clearSearch: () => {
      webViewRef.current?.injectJavaScript('window.__smilodonNativeBridge && window.__smilodonNativeBridge.clearSearch && window.__smilodonNativeBridge.clearSearch(); true;')
    },
    setItems: (nextItems) => {
      syncToWebView({ ...bridgePayload, items: nextItems, groupedItems: undefined })
    },
    setGroupedItems: (nextGroups) => {
      syncToWebView({ ...bridgePayload, groupedItems: nextGroups, items: undefined })
    },
    setValue: (nextValue) => {
      syncToWebView({ ...bridgePayload, value: toArrayValue(nextValue) })
    },
    updateConfig: (nextConfig) => {
      syncToWebView({ ...bridgePayload, config: { ...bridgePayload.config, ...nextConfig } })
    },
  }), [bridgePayload, syncToWebView])

  const onMessage = useCallback((event: WebViewMessageEvent) => {
    try {
      const message = JSON.parse(event.nativeEvent.data)
      switch (message.type) {
        case 'ready':
          setIsReady(true)
          syncToWebView(bridgePayload)
          return
        case 'height':
          if (typeof message.value === 'number') {
            setWebViewHeight(message.value)
          }
          return
        case 'select':
          onSelect?.(message.detail.item as SelectItem, message.detail.index as number)
          return
        case 'change': {
          const selectedValues = message.detail.selectedValues as Array<string | number>
          const selectedItems = message.detail.selectedItems as SelectItem[]
          const nextValue = multiple ? selectedValues : selectedValues[0] ?? ''
          if (value === undefined) {
            setInternalValue(nextValue)
          }
          onChange?.(nextValue, selectedItems)
          return
        }
        case 'open':
          onOpen?.()
          return
        case 'close':
          onClose?.()
          return
        case 'search':
          onSearch?.(message.detail.query as string)
          return
        case 'loadMore':
          onLoadMore?.(message.detail.page as number)
          return
        case 'create':
          onCreate?.(message.detail.value as string)
          return
        case 'clear':
          onClear?.({
            clearedSelection: Boolean(message.detail.clearedSelection),
            clearedSearch: Boolean(message.detail.clearedSearch),
          })
          return
        case 'diagnostic':
          onDiagnostic?.(message.detail as DiagnosticEventDetail)
          return
        default:
          return
      }
    } catch {
      return
    }
  }, [bridgePayload, multiple, onChange, onClear, onClose, onCreate, onDiagnostic, onLoadMore, onOpen, onSearch, onSelect, syncToWebView, value])

  const html = useMemo(() => createHtml(collapsedHeight), [collapsedHeight])

  return (
    <View style={[styles.container, { height: webViewHeight }, containerStyle]}>
      <WebView
        ref={webViewRef}
        originWhitelist={['*']}
        source={{ html }}
        javaScriptEnabled
        scrollEnabled={false}
        nestedScrollEnabled={false}
        onMessage={onMessage}
        automaticallyAdjustContentInsets={false}
        showsVerticalScrollIndicator={false}
      />
    </View>
  )
})

const styles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
})

export default Select
