// packages/solid/src/Select.tsx
import { createEffect, createSignal, onCleanup, onMount, on, type JSX } from 'solid-js'
import { render } from 'solid-js/web'
import type {
  SelectEventDetail,
  SearchEventDetail,
  ChangeEventDetail,
  LoadMoreEventDetail,
  ClearEventDetail,
  GroupedItem,
  ClassMap,
  RendererHelpers,
  DiagnosticEventDetail,
  LimitationPolicyMap,
  TrackingSnapshot,
  SelectCapabilitiesReport,
  LimitationState,
  GlobalSelectConfig,
  SelectionConfig,
  MultiSelectDisplayConfig,
  ScrollToSelectedConfig,
  StyleConfig,
} from '@smilodon/core'

export interface SelectItem {
  value: string | number
  label: string
  disabled?: boolean
  group?: string
  [key: string]: unknown
}

type SelectValue = string | number | Array<string | number>

type EnhancedSelectElement = HTMLElement & {
  setItems?: (items: SelectItem[]) => void
  setGroupedItems?: (groups: GroupedItem[]) => void
  getSelectedItems?: () => SelectItem[]
  getSelectedValues?: () => Array<string | number>
  setSelectedValues?: (values: Array<string | number>) => void
  updateConfig?: (config: unknown) => void
  open?: () => void
  close?: () => void
  clearSearch?: () => void
  setError?: (message: string) => void
  clearError?: () => void
  setRequired?: (required: boolean) => void
  validate?: () => boolean
  optionRenderer?: ((item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement) | undefined
  groupHeaderRenderer?: ((group: GroupedItem, index: number) => HTMLElement) | undefined
  classMap?: ClassMap | undefined
  getCapabilities?: () => SelectCapabilitiesReport
  getKnownLimitations?: () => LimitationState[]
  getTrackingSnapshot?: () => TrackingSnapshot
  clearTracking?: (source?: 'event' | 'style' | 'limitation' | 'all') => void
  setLimitationPolicies?: (policies: LimitationPolicyMap) => void
}

export interface SelectHandle {
  focus: () => void
  open: () => void
  close: () => void
  getSelectedItems: () => SelectItem[]
  getSelectedValues: () => Array<string | number>
  setItems: (items: SelectItem[]) => void
  setGroupedItems: (groups: GroupedItem[]) => void
  clear: () => void
  clearSearch: () => void
  updateConfig: (config: Partial<GlobalSelectConfig>) => void
  setError: (message: string) => void
  clearError: () => void
  setRequired: (required: boolean) => void
  validate: () => boolean
  getCapabilities: () => SelectCapabilitiesReport | undefined
  getKnownLimitations: () => LimitationState[]
  getTrackingSnapshot: () => TrackingSnapshot
  clearTracking: (source?: 'event' | 'style' | 'limitation' | 'all') => void
  setLimitationPolicies: (policies: LimitationPolicyMap) => void
}

export interface SelectProps {
  items?: SelectItem[]
  groupedItems?: GroupedItem[]
  groupHeaderRenderer?: (group: GroupedItem, index: number) => JSX.Element
  value?: SelectValue
  defaultValue?: SelectValue
  multiple?: boolean
  searchable?: boolean
  placeholder?: string
  disabled?: boolean
  required?: boolean
  error?: boolean
  infiniteScroll?: boolean
  pageSize?: number
  virtualized?: boolean
  maxSelections?: number
  selectionConfig?: Partial<SelectionConfig>
  multiSelectDisplay?: Partial<MultiSelectDisplayConfig>
  scrollToSelected?: Partial<ScrollToSelectedConfig>
  styles?: StyleConfig
  config?: Partial<GlobalSelectConfig>
  removeButtonIcon?: string
  disabledOptionBehavior?: {
    selectable?: boolean
    hoverable?: boolean
    focusable?: boolean
  }
  showSelectedIndicator?: boolean
  direction?: 'ltr' | 'rtl'
  placement?: 'bottom' | 'top' | 'auto'
  class?: string
  className?: string
  style?: JSX.CSSProperties
  expandable?: boolean
  clearable?: boolean
  clearSelectionOnClear?: boolean
  clearSearchOnClear?: boolean
  clearAriaLabel?: string
  clearIcon?: string
  classMap?: ClassMap
  optionRenderer?: (item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement
  customRenderer?: (item: SelectItem, index: number) => JSX.Element
  trackingEnabled?: boolean
  trackEvents?: boolean
  trackStyling?: boolean
  trackLimitations?: boolean
  emitDiagnostics?: boolean
  trackingMaxEntries?: number
  limitationPolicies?: LimitationPolicyMap
  autoMitigateRuntimeModeSwitch?: boolean
  onChange?: (value: SelectValue, items: SelectItem[]) => void
  onSelect?: (item: SelectItem, index: number) => void
  onOpen?: () => void
  onClose?: () => void
  onSearch?: (query: string) => void
  onLoadMore?: (page: number) => void
  onCreate?: (value: string) => void
  onClear?: (detail: { clearedSelection: boolean; clearedSearch: boolean }) => void
  onDiagnostic?: (detail: DiagnosticEventDetail) => void
  ref?: (handle: SelectHandle) => void
}

const defaultProps = {
  items: () => [] as SelectItem[],
  multiple: false,
  searchable: false,
  disabled: false,
  required: false,
  error: false,
  infiniteScroll: false,
  pageSize: 50,
  virtualized: true,
  showSelectedIndicator: true,
  placement: 'auto' as const,
  clearable: false,
  clearSelectionOnClear: true,
  clearSearchOnClear: true,
  trackingEnabled: false,
  trackEvents: true,
  trackStyling: true,
  trackLimitations: true,
  emitDiagnostics: false,
  trackingMaxEntries: 200,
  autoMitigateRuntimeModeSwitch: true,
}

export default function Select(rawProps: SelectProps) {
  const props = {
    ...defaultProps,
    ...rawProps,
    items: rawProps.items ?? defaultProps.items(),
  }

  let selectRef: EnhancedSelectElement | undefined
  const [isElementReady, setIsElementReady] = createSignal(false)
  const [internalValue, setInternalValue] = createSignal<SelectValue | undefined>(props.defaultValue)
  const [resolvedOptionRenderer, setResolvedOptionRenderer] = createSignal<SelectProps['optionRenderer'] | ((item: SelectItem, index: number, helpers?: RendererHelpers) => HTMLElement) | undefined>()
  const customRendererCache = new Map<number, { container: HTMLDivElement; dispose?: () => void }>()
  const groupHeaderRoots = new Map<number, { container: HTMLDivElement; dispose: () => void }>()

  const isControlled = () => rawProps.value !== undefined
  const currentValue = () => (isControlled() ? rawProps.value : internalValue())

  const toArrayValue = (value: SelectValue | undefined) =>
    value === undefined ? [] : Array.isArray(value) ? value : [value]

  const resolvePlacementMode = () => {
    const placement = rawProps.placement ?? props.placement
    return placement === 'auto' ? 'auto' : placement === 'top' ? 'top' : 'bottom'
  }

  const cleanupCustomRendererCache = () => {
    for (const entry of customRendererCache.values()) {
      entry.dispose?.()
      entry.container.remove()
    }
    customRendererCache.clear()
  }

  const cleanupGroupHeaderRenderers = () => {
    for (const entry of groupHeaderRoots.values()) {
      entry.dispose()
      entry.container.remove()
    }
    groupHeaderRoots.clear()
  }

  const safeCall = (fn: (el: EnhancedSelectElement) => void) => {
    if (!selectRef || !isElementReady()) return
    fn(selectRef)
  }

  const syncItems = (el: EnhancedSelectElement) => {
    if (rawProps.groupedItems?.length) {
      el.setGroupedItems?.(rawProps.groupedItems)
      return
    }

    if (!rawProps.items?.length) {
      el.setItems?.([])
      return
    }

    const first = rawProps.items[0]
    if (first && first.group !== undefined) {
      const grouped = Array.from(
        rawProps.items.reduce((map, item) => {
          const groupName = item.group ?? 'Ungrouped'
          const group = map.get(groupName)
          if (group) {
            group.options.push(item)
          } else {
            map.set(groupName, { label: groupName, options: [item] })
          }
          return map
        }, new Map<string, GroupedItem>()).values()
      )
      el.setGroupedItems?.(grouped)
      return
    }

    el.setItems?.(rawProps.items)
  }

  createEffect(
    on(
      [() => !!rawProps.optionRenderer, () => !!rawProps.customRenderer],
      ([hasOptionRenderer, hasCustomRenderer]: [boolean, boolean]) => {
        if (hasOptionRenderer) {
          cleanupCustomRendererCache()
          setResolvedOptionRenderer(() => (item: SelectItem, index: number, helpers?: RendererHelpers) =>
            rawProps.optionRenderer?.(item, index, helpers as RendererHelpers) ?? document.createElement('div')
          )
          return
        }

        if (hasCustomRenderer) {
          setResolvedOptionRenderer(() => (item: SelectItem, index: number) => {
            let entry = customRendererCache.get(index)
            if (!entry) {
              entry = { container: document.createElement('div') }
              customRendererCache.set(index, entry)
            }

            entry.dispose?.()
            entry.dispose = render(() => rawProps.customRenderer?.(item, index) ?? null, entry.container)
            return entry.container
          })
          return
        }

        cleanupCustomRendererCache()
        setResolvedOptionRenderer(undefined)
      },
      { defer: false }
    )
  )

  createEffect(() => {
    const ready = isElementReady()
    const renderer = resolvedOptionRenderer()
    if (!ready) return
    safeCall((el) => {
      el.optionRenderer = renderer
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    const classMap = rawProps.classMap
    if (!ready) return

    safeCall((el) => {
      el.classMap = classMap
    })
  })

  createEffect(() => {
    const items = rawProps.items
    const groups = rawProps.groupedItems
    const totalItems = groups?.length
      ? groups.reduce((count, group) => count + group.options.length, 0)
      : items?.length ?? 0

    for (const [index, entry] of customRendererCache.entries()) {
      if (index >= totalItems) {
        entry.dispose?.()
        entry.container.remove()
        customRendererCache.delete(index)
      }
    }
  })

  createEffect(() => {
    const totalGroups = rawProps.groupedItems?.length ?? 0

    for (const [index, entry] of groupHeaderRoots.entries()) {
      if (index >= totalGroups) {
        entry.dispose()
        entry.container.remove()
        groupHeaderRoots.delete(index)
      }
    }
  })

  createEffect(() => {
    if (!isElementReady()) return
    safeCall((el) => syncItems(el))
  })

  createEffect(() => {
    const ready = isElementReady()
    const renderer = rawProps.groupHeaderRenderer
    if (!ready) return

    safeCall((el) => {
      cleanupGroupHeaderRenderers()
      if (!renderer) {
        el.groupHeaderRenderer = undefined
        return
      }

      el.groupHeaderRenderer = (group: GroupedItem, index: number) => {
        const previous = groupHeaderRoots.get(index)
        previous?.dispose()
        previous?.container.remove()

        const container = document.createElement('div')
        const dispose = render(() => renderer(group, index), container)
        groupHeaderRoots.set(index, { container, dispose })
        return container
      }
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    const placement = rawProps.placement ?? props.placement
    if (!ready || !selectRef) return
    if (placement) {
      selectRef.setAttribute('placement', placement)
    }
  })

  createEffect(() => {
    const ready = isElementReady()
    const value = currentValue()
    if (!ready || value === undefined) return

    safeCall((el) => {
      const currentSelected = el.getSelectedValues?.() ?? []
      const nextValues = toArrayValue(value)
      const hasChanged =
        currentSelected.length !== nextValues.length ||
        !currentSelected.every((selectedValue, index) => selectedValue === nextValues[index])

      if (hasChanged) {
        el.setSelectedValues?.(nextValues)
      }
    })
  })

  createEffect(() => {
    const ready = isElementReady()
    if (!ready) return

    safeCall((el) => {
      el.updateConfig?.({
        searchable: rawProps.searchable ?? props.searchable,
        placeholder: rawProps.placeholder,
        enabled: !(rawProps.disabled ?? props.disabled),
        virtualize: rawProps.virtualized ?? props.virtualized,
        dropdownPlacement: {
          mode: resolvePlacementMode(),
        },
        direction: rawProps.direction,
        selection: {
          ...(rawProps.selectionConfig ?? {}),
          mode: (rawProps.multiple ?? props.multiple) ? 'multi' : 'single',
          maxSelections: rawProps.maxSelections,
          removeButtonIcon: rawProps.removeButtonIcon,
            disabledOptionBehavior: rawProps.disabledOptionBehavior,
            showSelectedIndicator: rawProps.showSelectedIndicator ?? props.showSelectedIndicator,
        },
        multiSelectDisplay: rawProps.multiSelectDisplay,
        infiniteScroll: {
          enabled: rawProps.infiniteScroll ?? props.infiniteScroll,
          pageSize: rawProps.pageSize ?? props.pageSize,
        },
        scrollToSelected: {
          enabled: true,
          ...(rawProps.scrollToSelected ?? {}),
        },
        styles: rawProps.styles,
        expandable: {
          enabled: rawProps.expandable,
        },
        clearControl: {
          enabled: rawProps.clearable ?? props.clearable,
          clearSelection: rawProps.clearSelectionOnClear ?? props.clearSelectionOnClear,
          clearSearch: rawProps.clearSearchOnClear ?? props.clearSearchOnClear,
          ariaLabel: rawProps.clearAriaLabel,
          icon: rawProps.clearIcon,
        },
        tracking: {
          enabled: rawProps.trackingEnabled ?? props.trackingEnabled,
          events: rawProps.trackEvents ?? props.trackEvents,
          styling: rawProps.trackStyling ?? props.trackStyling,
          limitations: rawProps.trackLimitations ?? props.trackLimitations,
          emitDiagnostics: rawProps.emitDiagnostics ?? props.emitDiagnostics,
          maxEntries: rawProps.trackingMaxEntries ?? props.trackingMaxEntries,
        },
        limitations: {
          policies: rawProps.limitationPolicies,
          autoMitigateRuntimeModeSwitch:
            rawProps.autoMitigateRuntimeModeSwitch ?? props.autoMitigateRuntimeModeSwitch,
        },
      })
      if (rawProps.config) {
        el.updateConfig?.(rawProps.config)
      }
    })
  })

  const waitForUpgrade = async () => {
    if (typeof window === 'undefined') return

    if (!customElements.get('enhanced-select')) {
      await import('@smilodon/core')
    }

    if (!selectRef) return

    try {
      await customElements.whenDefined('enhanced-select')
    } catch {
      // ignore
    }

    for (let index = 0; index < 5; index += 1) {
      if (selectRef && typeof selectRef.setItems === 'function') {
        setIsElementReady(true)
        if (resolvedOptionRenderer()) {
          selectRef.optionRenderer = resolvedOptionRenderer()
        }
        if (rawProps.classMap) {
          selectRef.classMap = rawProps.classMap
        }
        return
      }
      await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()))
    }

    setIsElementReady(Boolean(selectRef && typeof selectRef.setItems === 'function'))
    if (selectRef && resolvedOptionRenderer()) {
      selectRef.optionRenderer = resolvedOptionRenderer()
    }
    if (selectRef && rawProps.classMap) {
      selectRef.classMap = rawProps.classMap
    }
  }

  const handleSelect = (event: Event) => {
    const customEvent = event as CustomEvent<SelectEventDetail>
    rawProps.onSelect?.(customEvent.detail.item as SelectItem, customEvent.detail.index)
  }

  const handleChange = (event: Event) => {
    const customEvent = event as CustomEvent<ChangeEventDetail>
    const values = customEvent.detail.selectedValues as Array<string | number>
    const nextValue = (rawProps.multiple ?? props.multiple) ? values : values[0] ?? ''

    if (!isControlled()) {
      setInternalValue(nextValue)
    }

    rawProps.onChange?.(nextValue, customEvent.detail.selectedItems as SelectItem[])
  }

  const handleSearch = (event: Event) => {
    const customEvent = event as CustomEvent<SearchEventDetail>
    rawProps.onSearch?.(customEvent.detail.query)
  }

  const handleLoadMore = (event: Event) => {
    const customEvent = event as CustomEvent<LoadMoreEventDetail>
    rawProps.onLoadMore?.(customEvent.detail.page)
  }

  const handleCreate = (event: Event) => {
    const customEvent = event as CustomEvent<{ value: string }>
    rawProps.onCreate?.(customEvent.detail.value)
  }

  const handleClear = (event: Event) => {
    const customEvent = event as CustomEvent<ClearEventDetail>
    rawProps.onClear?.({
      clearedSelection: customEvent.detail.clearedSelection,
      clearedSearch: customEvent.detail.clearedSearch,
    })
  }

  const handleDiagnostic = (event: Event) => {
    const customEvent = event as CustomEvent<DiagnosticEventDetail>
    rawProps.onDiagnostic?.(customEvent.detail)
  }

  const handleOpen = () => rawProps.onOpen?.()
  const handleClose = () => rawProps.onClose?.()

  const handle: SelectHandle = {
    focus: () => selectRef?.focus(),
    open: () => selectRef?.open?.(),
    close: () => selectRef?.close?.(),
    getSelectedItems: () => selectRef?.getSelectedItems?.() ?? [],
    getSelectedValues: () => selectRef?.getSelectedValues?.() ?? [],
    setItems: (items) => selectRef?.setItems?.(items),
    setGroupedItems: (groups) => selectRef?.setGroupedItems?.(groups),
    clear: () => {
      selectRef?.setSelectedValues?.([])
      if (!isControlled()) {
        setInternalValue((rawProps.multiple ?? props.multiple) ? [] : '')
      }
      rawProps.onChange?.((rawProps.multiple ?? props.multiple) ? [] : '', [])
    },
    clearSearch: () => selectRef?.clearSearch?.(),
    updateConfig: (config) => selectRef?.updateConfig?.(config),
    setError: (message) => selectRef?.setError?.(message),
    clearError: () => selectRef?.clearError?.(),
    setRequired: (required) => selectRef?.setRequired?.(required),
    validate: () => selectRef?.validate?.() ?? true,
    getCapabilities: () => selectRef?.getCapabilities?.(),
    getKnownLimitations: () => selectRef?.getKnownLimitations?.() ?? [],
    getTrackingSnapshot: () => selectRef?.getTrackingSnapshot?.() ?? { events: [], styles: [], limitations: [] },
    clearTracking: (source) => selectRef?.clearTracking?.(source),
    setLimitationPolicies: (policies) => selectRef?.setLimitationPolicies?.(policies),
  }

  onMount(async () => {
    await waitForUpgrade()
    if (!selectRef || !isElementReady()) return

    props.ref?.(handle)

    syncItems(selectRef)

    const initialValues = toArrayValue(currentValue())
    if (initialValues.length) {
      selectRef.setSelectedValues?.(initialValues)
    }

    selectRef.addEventListener('select', handleSelect as EventListener)
    selectRef.addEventListener('change', handleChange as EventListener)
    selectRef.addEventListener('open', handleOpen as EventListener)
    selectRef.addEventListener('close', handleClose as EventListener)
    selectRef.addEventListener('search', handleSearch as EventListener)
    selectRef.addEventListener('loadMore', handleLoadMore as EventListener)
    selectRef.addEventListener('create', handleCreate as EventListener)
    selectRef.addEventListener('clear', handleClear as EventListener)
    selectRef.addEventListener('diagnostic', handleDiagnostic as EventListener)
  })

  onCleanup(() => {
    cleanupCustomRendererCache()
    cleanupGroupHeaderRenderers()

    if (!selectRef) return

    selectRef.removeEventListener('select', handleSelect as EventListener)
    selectRef.removeEventListener('change', handleChange as EventListener)
    selectRef.removeEventListener('open', handleOpen as EventListener)
    selectRef.removeEventListener('close', handleClose as EventListener)
    selectRef.removeEventListener('search', handleSearch as EventListener)
    selectRef.removeEventListener('loadMore', handleLoadMore as EventListener)
    selectRef.removeEventListener('create', handleCreate as EventListener)
    selectRef.removeEventListener('clear', handleClear as EventListener)
    selectRef.removeEventListener('diagnostic', handleDiagnostic as EventListener)
  })

  return (
    <enhanced-select
      ref={(element: Element) => {
        selectRef = element as EnhancedSelectElement
      }}
      class={rawProps.class ?? rawProps.className}
      style={rawProps.style as JSX.CSSProperties}
        dir={rawProps.direction}
    />
  )
}

// packages/svelte/src/Select.svelte
<!--
  Smilodon Select Component for Svelte
  
  A production-ready, accessible select component with advanced features:
  - Single and multi-select modes
  - Searchable with client or server-side filtering
  - Infinite scroll and virtual scrolling for large datasets
  - Grouped options
  - Custom rendering
  - Full keyboard navigation
  - WCAG 2.1 AAA compliant
  
  @example
  <Select
    {items}
    bind:value={selectedValue}
    searchable
    placeholder="Select an option..."
  />
-->

<script lang="ts" context="module">
  export interface SelectItem {
    value: string | number;
    label: string;
    disabled?: boolean;
    group?: string;
    [key: string]: any;
  }
</script>

<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import type {
    SelectEventDetail,
    OpenEventDetail,
    CloseEventDetail,
    SearchEventDetail,
    ChangeEventDetail,
    LoadMoreEventDetail,
    ClearEventDetail,
    GroupedItem,
    DiagnosticEventDetail,
    LimitationPolicyMap,
  } from '@smilodon/core';

  // Props
  export let items: SelectItem[] = [];
  export let groupedItems: GroupedItem[] | undefined = undefined;
  export let value: string | number | (string | number)[] | undefined = undefined;
  export let defaultValue: string | number | (string | number)[] | undefined = undefined;
  export let multiple: boolean = false;
  export let searchable: boolean = false;
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let required: boolean = false;
  export let error: boolean = false;
  export let infiniteScroll: boolean = false;
  export let pageSize: number = 50;
  export let virtualized: boolean = true;
  export let maxSelections: number | undefined = undefined;
  export let placement: 'bottom' | 'top' | 'auto' = 'auto';
  export let className: string = '';
  export let style: string = '';
  export let clearable: boolean = false;
  export let clearSelectionOnClear: boolean = true;
  export let clearSearchOnClear: boolean = true;
  export let clearAriaLabel: string = 'Clear selection and search';
  export let clearIcon: string = '×';
  export let optionRenderer: ((item: SelectItem, index: number, helpers: any) => HTMLElement) | undefined = undefined;
  export let trackingEnabled: boolean = false;
  export let trackEvents: boolean = true;
  export let trackStyling: boolean = true;
  export let trackLimitations: boolean = true;
  export let emitDiagnostics: boolean = false;
  export let trackingMaxEntries: number = 200;
  export let limitationPolicies: LimitationPolicyMap | undefined = undefined;
  export let autoMitigateRuntimeModeSwitch: boolean = true;

  const dispatch = createEventDispatcher<{
    change: { value: string | number | (string | number)[]; selectedItems: SelectItem[] };
    select: { item: SelectItem; index: number };
    open: void;
    close: void;
    search: { query: string };
    loadMore: { page: number };
    create: { value: string };
    clear: { clearedSelection: boolean; clearedSearch: boolean };
    diagnostic: DiagnosticEventDetail;
  }>();

  let selectRef: HTMLElement;
  let internalValue: string | number | (string | number)[] | undefined = defaultValue;

  // Stable wrapper to handle optionRenderer updates without triggering infinite loops
  const resolvedOptionRenderer = (item: SelectItem, index: number, helpers: any) => {
    return optionRenderer ? optionRenderer(item, index, helpers) : document.createElement('div');
  };

  // Check if component is controlled
  $: isControlled = value !== undefined;
  $: currentValue = isControlled ? value : internalValue;

  // Event handlers
  function handleSelect(e: Event) {
    const customEvent = e as CustomEvent<SelectEventDetail>;
    const { item, index } = customEvent.detail;
    dispatch('select', { item: item as SelectItem, index });
  }

  function handleChange(e: Event) {
    const customEvent = e as CustomEvent<ChangeEventDetail>;
    const { selectedItems, selectedValues } = customEvent.detail;

    const values = selectedValues as (string | number)[];

    // Update internal value in uncontrolled mode
    if (!isControlled) {
      internalValue = multiple ? values : values[0];
    }

    // Emit change event
    const newValue = multiple ? values : values[0];
    value = newValue; // Update binding
    dispatch('change', { value: newValue, selectedItems: selectedItems as SelectItem[] });
  }

  function handleOpen() {
    dispatch('open');
  }

  function handleClose() {
    dispatch('close');
  }

  function handleSearch(e: Event) {
    const customEvent = e as CustomEvent<SearchEventDetail>;
    dispatch('search', { query: customEvent.detail.query });
  }

  function handleLoadMore(e: Event) {
    const customEvent = e as CustomEvent<LoadMoreEventDetail>;
    dispatch('loadMore', { page: customEvent.detail.page });
  }

  function handleCreate(e: Event) {
    const customEvent = e as CustomEvent<{ value: string }>;
    dispatch('create', { value: customEvent.detail.value });
  }

  function handleClear(e: Event) {
    const customEvent = e as CustomEvent<ClearEventDetail>;
    dispatch('clear', {
      clearedSelection: customEvent.detail.clearedSelection,
      clearedSearch: customEvent.detail.clearedSearch,
    });
  }

  function handleDiagnostic(e: Event) {
    const customEvent = e as CustomEvent<DiagnosticEventDetail>;
    dispatch('diagnostic', customEvent.detail);
  }

  function updateConfig() {
    if (!selectRef) return;
    (selectRef as any).updateConfig?.({
      searchable,
      placeholder,
      enabled: !disabled,
      selection: {
        mode: multiple ? 'multi' : 'single',
        maxSelections,
      },
      infiniteScroll: {
        enabled: infiniteScroll,
        pageSize,
      },
      clearControl: {
        enabled: clearable,
        clearSelection: clearSelectionOnClear,
        clearSearch: clearSearchOnClear,
        ariaLabel: clearAriaLabel,
        icon: clearIcon,
      },
      tracking: {
        enabled: trackingEnabled,
        events: trackEvents,
        styling: trackStyling,
        limitations: trackLimitations,
        emitDiagnostics,
        maxEntries: trackingMaxEntries,
      },
      limitations: {
        policies: limitationPolicies,
        autoMitigateRuntimeModeSwitch,
      },
    });
  }

  onMount(() => {
    if (!selectRef) return;

    const element = selectRef;

    // Set initial attributes
    if (placeholder) element.setAttribute('placeholder', placeholder);
    if (disabled) element.setAttribute('disabled', '');
    if (required) element.setAttribute('required', '');
    if (error) element.setAttribute('error', '');
    if (searchable) element.setAttribute('searchable', '');
    if (multiple) element.setAttribute('multiple', '');
    if (virtualized) element.setAttribute('virtualized', '');
    if (infiniteScroll) element.setAttribute('infinite-scroll', '');
    if (pageSize) element.setAttribute('page-size', String(pageSize));
    if (maxSelections) element.setAttribute('max-selections', String(maxSelections));
    if (placement) element.setAttribute('placement', placement);

    if (optionRenderer) {
      (element as any).optionRenderer = resolvedOptionRenderer;
    }

    // Set initial items
    if (items?.length) {
      // Auto-convert flat items with `group` property into groupedItems
      const first = items[0];
      if (first && (first as any).group !== undefined) {
        const map = new Map<string, any[]>();
        items.forEach((it: any) => {
          const g = it.group ?? 'Ungrouped';
          if (!map.has(g)) map.set(g, []);
          map.get(g)!.push(it);
        });
        const groups = Array.from(map.entries()).map(([label, options]) => ({ label, options }));
        (element as any).setGroupedItems(groups);
      } else {
        (element as any).setItems(items);
      }
    }
    if (groupedItems?.length) {
      (element as any).setGroupedItems(groupedItems);
    }

    // Set initial value
    if (currentValue !== undefined) {
      const values = Array.isArray(currentValue) ? currentValue : [currentValue];
      (element as any).setSelectedValues(values);
    }

    // Add event listeners
    element.addEventListener('select', handleSelect as EventListener);
    element.addEventListener('change', handleChange as EventListener);
    element.addEventListener('open', handleOpen as EventListener);
    element.addEventListener('close', handleClose as EventListener);
    element.addEventListener('search', handleSearch as EventListener);
    element.addEventListener('loadMore', handleLoadMore as EventListener);
    element.addEventListener('create', handleCreate as EventListener);
    element.addEventListener('clear', handleClear as EventListener);
    element.addEventListener('diagnostic', handleDiagnostic as EventListener);

    updateConfig();
  });

  onDestroy(() => {
    if (!selectRef) return;

    const element = selectRef;

    // Remove event listeners
    element.removeEventListener('select', handleSelect as EventListener);
    element.removeEventListener('change', handleChange as EventListener);
    element.removeEventListener('open', handleOpen as EventListener);
    element.removeEventListener('close', handleClose as EventListener);
    element.removeEventListener('search', handleSearch as EventListener);
    element.removeEventListener('loadMore', handleLoadMore as EventListener);
    element.removeEventListener('create', handleCreate as EventListener);
    element.removeEventListener('clear', handleClear as EventListener);
    element.removeEventListener('diagnostic', handleDiagnostic as EventListener);
  });

  // Reactive updates
  $: if (selectRef && items) {
    if (typeof (selectRef as any).setItems === 'function') {
      (selectRef as any).setItems(items);
    }
  }

  $: if (selectRef && groupedItems) {
    if (typeof (selectRef as any).setGroupedItems === 'function') {
      (selectRef as any).setGroupedItems(groupedItems);
    }
  }

  $: if (selectRef && currentValue !== undefined) {
    if (typeof (selectRef as any).setSelectedValues === 'function') {
      const values = Array.isArray(currentValue) ? currentValue : [currentValue];
      (selectRef as any).setSelectedValues(values);
    }
  }

  $: if (selectRef) {
    if (placeholder) selectRef.setAttribute('placeholder', placeholder);
    if (disabled) {
      selectRef.setAttribute('disabled', '');
    } else {
      selectRef.removeAttribute('disabled');
    }
    if (searchable) {
      selectRef.setAttribute('searchable', '');
    } else {
      selectRef.removeAttribute('searchable');
    }
    if (multiple) {
      selectRef.setAttribute('multiple', '');
    } else {
      selectRef.removeAttribute('multiple');
    }
    if (virtualized) {
      selectRef.setAttribute('virtualized', '');
    } else {
      selectRef.removeAttribute('virtualized');
    }

    if (optionRenderer) {
      if ((selectRef as any).optionRenderer !== resolvedOptionRenderer) {
        (selectRef as any).optionRenderer = resolvedOptionRenderer;
      }
    } else if ((selectRef as any).optionRenderer === resolvedOptionRenderer) {
      (selectRef as any).optionRenderer = undefined;
    }
  }

  $: if (selectRef) {
    updateConfig();
  }

  // Public methods
  export function open() {
    if (typeof (selectRef as any)?.open === 'function') {
      (selectRef as any).open();
    }
  }

  export function close() {
    if (typeof (selectRef as any)?.close === 'function') {
      (selectRef as any).close();
    }
  }

  export function focus() {
    if (typeof (selectRef as any)?.focus === 'function') {
      (selectRef as any).focus();
    }
  }

  export function setItems(newItems: SelectItem[]) {
    (selectRef as any)?.setItems(newItems);
  }

  export function setGroupedItems(groups: GroupedItem[]) {
    (selectRef as any)?.setGroupedItems(groups);
  }

  export function clear() {
    (selectRef as any)?.setSelectedValues([]);
    if (!isControlled) {
      internalValue = multiple ? [] : undefined;
    }
    const newValue = multiple ? [] : '';
    value = newValue as any;
    dispatch('change', { value: newValue as any, selectedItems: [] });
  }

  export function getCapabilities() {
    return (selectRef as any)?.getCapabilities?.();
  }

  export function getKnownLimitations() {
    return (selectRef as any)?.getKnownLimitations?.() || [];
  }

  export function getTrackingSnapshot() {
    return (selectRef as any)?.getTrackingSnapshot?.() || { events: [], styles: [], limitations: [] };
  }

  export function clearTracking(source?: 'event' | 'style' | 'limitation' | 'all') {
    (selectRef as any)?.clearTracking?.(source);
  }

  export function setLimitationPolicies(policies: LimitationPolicyMap) {
    (selectRef as any)?.setLimitationPolicies?.(policies);
  }
</script>

<enhanced-select
  bind:this={selectRef}
  class={className}
  {style}
/>

<style>
  /* Component uses web component styling from @smilodon/core */
</style>
