// packages/angular/src/select.component.ts
/**
 * Smilodon Select Component for Angular
 * 
 * A production-ready, accessible select component with advanced features:
 * - Single and multi-select modes
 * - Searchable with client or server-side filtering
 * - Infinite scroll and virtual scrolling for large datasets
 * - Grouped options
 * - Custom rendering
 * - Full keyboard navigation
 * - WCAG 2.1 AAA compliant
 * - Full Angular Forms integration (ControlValueAccessor)
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  OnInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
  forwardRef,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import '@smilodon/core'; // Register web components
import type {
  SelectEventDetail,
  ChangeEventDetail,
  SearchEventDetail,
  LoadMoreEventDetail,
  GroupedItem,
} from '@smilodon/core';

export interface SelectItem {
  value: string | number;
  label: string;
  disabled?: boolean;
  group?: string;
  [key: string]: any;
}

@Component({
  selector: 'smilodon-select',
  template: `
    <enhanced-select
      #selectElement
      [attr.placeholder]="placeholder"
      [attr.disabled]="disabled ? '' : null"
      [attr.required]="required ? '' : null"
      [attr.error]="error ? '' : null"
      [attr.searchable]="searchable ? '' : null"
      [attr.multiple]="multiple ? '' : null"
      [attr.virtualized]="virtualized ? '' : null"
      [attr.infinite-scroll]="infiniteScroll ? '' : null"
      [attr.page-size]="pageSize"
      [attr.max-selections]="maxSelections"
      [attr.placement]="placement"
      [class]="className"
      [style]="styleString"
      (select)="onSelectEvent($event)"
      (change)="onChangeEvent($event)"
      (open)="onOpenEvent()"
      (close)="onCloseEvent()"
      (search)="onSearchEvent($event)"
      (loadMore)="onLoadMoreEvent($event)"
      (create)="onCreateEvent($event)"
    ></enhanced-select>
  `,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => SelectComponent),
      multi: true,
    },
  ],
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SelectComponent implements OnInit, OnDestroy, OnChanges, ControlValueAccessor {
  @ViewChild('selectElement', { static: true }) selectElementRef!: ElementRef<HTMLElement>;

  // Props
  @Input() items: SelectItem[] = [];
  @Input() groupedItems?: GroupedItem[];
  @Input() value?: string | number | (string | number)[];
  @Input() multiple = false;
  @Input() searchable = false;
  @Input() placeholder = '';
  @Input() disabled = false;
  @Input() required = false;
  @Input() error = false;
  @Input() infiniteScroll = false;
  @Input() pageSize = 50;
  @Input() virtualized = true;
  @Input() maxSelections?: number;
  @Input() placement: 'bottom' | 'top' | 'auto' = 'auto';
  @Input() className = '';
  @Input() style: { [key: string]: string } = {};
  @Input() config: any = {};

  // Events
  @Output() selectEvent = new EventEmitter<{ item: SelectItem; index: number }>();
  @Output() changeEvent = new EventEmitter<{ value: string | number | (string | number)[]; selectedItems: SelectItem[] }>();
  @Output() openEvent = new EventEmitter<void>();
  @Output() closeEvent = new EventEmitter<void>();
  @Output() searchEvent = new EventEmitter<{ query: string }>();
  @Output() loadMoreEvent = new EventEmitter<{ page: number }>();
  @Output() createEvent = new EventEmitter<{ value: string }>();

  // ControlValueAccessor
  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};

  get styleString(): string {
    return Object.entries(this.style)
      .map(([key, value]) => `${key}: ${value}`)
      .join('; ');
  }

  ngOnInit(): void {
    const element = this.selectElementRef.nativeElement as any;

    // Set initial items
    if (this.items?.length) {
      element.setItems(this.items);
    }
    if (this.groupedItems?.length) {
      element.setGroupedItems(this.groupedItems);
    }

    // Set initial value
    if (this.value !== undefined) {
      const values = Array.isArray(this.value) ? this.value : [this.value];
      element.setSelectedValues(values);
    }

    if (this.config) {
      element.updateConfig(this.config);
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    const element = this.selectElementRef?.nativeElement as any;
    if (!element) return;

    // Update items
    if (changes['items'] && !changes['items'].firstChange) {
      element.setItems(this.items);
    }

    if (changes['config'] && !changes['config'].firstChange) {
      element.updateConfig(this.config);
    }

    // Update grouped items
    if (changes['groupedItems'] && !changes['groupedItems'].firstChange) {
      element.setGroupedItems(this.groupedItems);
    }

    // Update value
    if (changes['value'] && !changes['value'].firstChange && this.value !== undefined) {
      const values = Array.isArray(this.value) ? this.value : [this.value];
      element.setSelectedValues(values);
    }
  }

  ngOnDestroy(): void {
    // Cleanup handled by Angular
  }

  // Event handlers
  onSelectEvent(event: Event): void {
    const customEvent = event as CustomEvent<SelectEventDetail>;
    const { item, index } = customEvent.detail;
    this.selectEvent.emit({ item: item as SelectItem, index });
  }

  onChangeEvent(event: Event): void {
    const customEvent = event as CustomEvent<ChangeEventDetail>;
    const { selectedItems, selectedValues } = customEvent.detail;

    const values = selectedValues as (string | number)[];
    const newValue = this.multiple ? values : values[0];

    // Emit Angular event
    this.changeEvent.emit({ value: newValue, selectedItems: selectedItems as SelectItem[] });

    // Notify form control
    this.onChange(newValue);
    this.onTouched();
  }

  onOpenEvent(): void {
    this.openEvent.emit();
  }

  onCloseEvent(): void {
    this.closeEvent.emit();
    this.onTouched();
  }

  onSearchEvent(event: Event): void {
    const customEvent = event as CustomEvent<SearchEventDetail>;
    this.searchEvent.emit({ query: customEvent.detail.query });
  }

  onLoadMoreEvent(event: Event): void {
    const customEvent = event as CustomEvent<LoadMoreEventDetail>;
    this.loadMoreEvent.emit({ page: customEvent.detail.page });
  }

  onCreateEvent(event: Event): void {
    const customEvent = event as CustomEvent<{ value: string }>;
    this.createEvent.emit({ value: customEvent.detail.value });
  }

  // ControlValueAccessor implementation
  writeValue(value: any): void {
    if (value !== undefined) {
      this.value = value;
      const element = this.selectElementRef?.nativeElement as any;
      if (element) {
        const values = Array.isArray(value) ? value : [value];
        element.setSelectedValues(values);
      }
    }
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  // Public API methods
  open(): void {
    (this.selectElementRef.nativeElement as any)?.open();
  }

  close(): void {
    (this.selectElementRef.nativeElement as any)?.close();
  }

  focus(): void {
    this.selectElementRef.nativeElement?.focus();
  }

  setItems(items: SelectItem[]): void {
    this.items = items;
    (this.selectElementRef.nativeElement as any)?.setItems(items);
  }

  setGroupedItems(groups: GroupedItem[]): void {
    this.groupedItems = groups;
    (this.selectElementRef.nativeElement as any)?.setGroupedItems(groups);
  }

  clear(): void {
    (this.selectElementRef.nativeElement as any)?.setSelectedValues([]);
    const newValue = this.multiple ? [] : '';
    this.onChange(newValue);
    this.changeEvent.emit({ value: newValue as any, selectedItems: [] });
  }
}

// packages/svelte/src/Select.svelte
<!--
  Smilodon Select Component for Svelte
  
  A production-ready, accessible select component with advanced features:
  - Single and multi-select modes
  - Searchable with client or server-side filtering
  - Infinite scroll and virtual scrolling for large datasets
  - Grouped options
  - Custom rendering
  - Full keyboard navigation
  - WCAG 2.1 AAA compliant
  
  @example
  <Select
    {items}
    bind:value={selectedValue}
    searchable
    placeholder="Select an option..."
  />
-->

<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import type {
    SelectEventDetail,
    OpenEventDetail,
    CloseEventDetail,
    SearchEventDetail,
    ChangeEventDetail,
    LoadMoreEventDetail,
    GroupedItem,
  } from '@smilodon/core';

  export interface SelectItem {
    value: string | number;
    label: string;
    disabled?: boolean;
    group?: string;
    [key: string]: any;
  }

  // Props
  export let items: SelectItem[] = [];
  export let groupedItems: GroupedItem[] | undefined = undefined;
  export let value: string | number | (string | number)[] | undefined = undefined;
  export let defaultValue: string | number | (string | number)[] | undefined = undefined;
  export let multiple: boolean = false;
  export let searchable: boolean = false;
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let required: boolean = false;
  export let error: boolean = false;
  export let infiniteScroll: boolean = false;
  export let pageSize: number = 50;
  export let virtualized: boolean = true;
  export let maxSelections: number | undefined = undefined;
  export let placement: 'bottom' | 'top' | 'auto' = 'auto';
  export let className: string = '';
  export let style: string = '';
  export let optionRenderer: ((item: SelectItem, index: number, helpers: any) => HTMLElement) | undefined = undefined;

  const dispatch = createEventDispatcher<{
    change: { value: string | number | (string | number)[]; selectedItems: SelectItem[] };
    select: { item: SelectItem; index: number };
    open: void;
    close: void;
    search: { query: string };
    loadMore: { page: number };
    create: { value: string };
  }>();

  let selectRef: HTMLElement;
  let internalValue: string | number | (string | number)[] | undefined = defaultValue;

  // Check if component is controlled
  $: isControlled = value !== undefined;
  $: currentValue = isControlled ? value : internalValue;

  // Event handlers
  function handleSelect(e: Event) {
    const customEvent = e as CustomEvent<SelectEventDetail>;
    const { item, index } = customEvent.detail;
    dispatch('select', { item: item as SelectItem, index });
  }

  function handleChange(e: Event) {
    const customEvent = e as CustomEvent<ChangeEventDetail>;
    const { selectedItems, selectedValues } = customEvent.detail;

    const values = selectedValues as (string | number)[];

    // Update internal value in uncontrolled mode
    if (!isControlled) {
      internalValue = multiple ? values : values[0];
    }

    // Emit change event
    const newValue = multiple ? values : values[0];
    value = newValue; // Update binding
    dispatch('change', { value: newValue, selectedItems: selectedItems as SelectItem[] });
  }

  function handleOpen() {
    dispatch('open');
  }

  function handleClose() {
    dispatch('close');
  }

  function handleSearch(e: Event) {
    const customEvent = e as CustomEvent<SearchEventDetail>;
    dispatch('search', { query: customEvent.detail.query });
  }

  function handleLoadMore(e: Event) {
    const customEvent = e as CustomEvent<LoadMoreEventDetail>;
    dispatch('loadMore', { page: customEvent.detail.page });
  }

  function handleCreate(e: Event) {
    const customEvent = e as CustomEvent<{ value: string }>;
    dispatch('create', { value: customEvent.detail.value });
  }

  onMount(() => {
    if (!selectRef) return;

    const element = selectRef;

    // Set initial attributes
    if (placeholder) element.setAttribute('placeholder', placeholder);
    if (disabled) element.setAttribute('disabled', '');
    if (required) element.setAttribute('required', '');
    if (error) element.setAttribute('error', '');
    if (searchable) element.setAttribute('searchable', '');
    if (multiple) element.setAttribute('multiple', '');
    if (virtualized) element.setAttribute('virtualized', '');
    if (infiniteScroll) element.setAttribute('infinite-scroll', '');
    if (pageSize) element.setAttribute('page-size', String(pageSize));
    if (maxSelections) element.setAttribute('max-selections', String(maxSelections));
    if (placement) element.setAttribute('placement', placement);

    if (optionRenderer) {
      (element as any).optionRenderer = optionRenderer;
    }

    // Set initial items
    if (items?.length) {
      (element as any).setItems(items);
    }
    if (groupedItems?.length) {
      (element as any).setGroupedItems(groupedItems);
    }

    // Set initial value
    if (currentValue !== undefined) {
      const values = Array.isArray(currentValue) ? currentValue : [currentValue];
      (element as any).setSelectedValues(values);
    }

    // Add event listeners
    element.addEventListener('select', handleSelect as EventListener);
    element.addEventListener('change', handleChange as EventListener);
    element.addEventListener('open', handleOpen as EventListener);
    element.addEventListener('close', handleClose as EventListener);
    element.addEventListener('search', handleSearch as EventListener);
    element.addEventListener('loadMore', handleLoadMore as EventListener);
    element.addEventListener('create', handleCreate as EventListener);
  });

  onDestroy(() => {
    if (!selectRef) return;

    const element = selectRef;

    // Remove event listeners
    element.removeEventListener('select', handleSelect as EventListener);
    element.removeEventListener('change', handleChange as EventListener);
    element.removeEventListener('open', handleOpen as EventListener);
    element.removeEventListener('close', handleClose as EventListener);
    element.removeEventListener('search', handleSearch as EventListener);
    element.removeEventListener('loadMore', handleLoadMore as EventListener);
    element.removeEventListener('create', handleCreate as EventListener);
  });

  // Reactive updates
  $: if (selectRef && items) {
    (selectRef as any).setItems(items);
  }

  $: if (selectRef && groupedItems) {
    (selectRef as any).setGroupedItems(groupedItems);
  }

  $: if (selectRef && currentValue !== undefined) {
    const values = Array.isArray(currentValue) ? currentValue : [currentValue];
    (selectRef as any).setSelectedValues(values);
  }

  $: if (selectRef) {
    if (placeholder) selectRef.setAttribute('placeholder', placeholder);
    if (disabled) {
      selectRef.setAttribute('disabled', '');
    } else {
      selectRef.removeAttribute('disabled');
    }
    if (searchable) {
      selectRef.setAttribute('searchable', '');
    } else {
      selectRef.removeAttribute('searchable');
    }
    if (multiple) {
      selectRef.setAttribute('multiple', '');
    } else {
      selectRef.removeAttribute('multiple');
    }
    if (virtualized) {
      selectRef.setAttribute('virtualized', '');
    } else {
      selectRef.removeAttribute('virtualized');
    }

    if (optionRenderer) {
      (selectRef as any).optionRenderer = optionRenderer;
    }
  }

  // Public methods
  export function open() {
    (selectRef as any)?.open();
  }

  export function close() {
    (selectRef as any)?.close();
  }

  export function focus() {
    selectRef?.focus();
  }

  export function setItems(newItems: SelectItem[]) {
    (selectRef as any)?.setItems(newItems);
  }

  export function setGroupedItems(groups: GroupedItem[]) {
    (selectRef as any)?.setGroupedItems(groups);
  }

  export function clear() {
    (selectRef as any)?.setSelectedValues([]);
    if (!isControlled) {
      internalValue = multiple ? [] : undefined;
    }
    const newValue = multiple ? [] : '';
    value = newValue as any;
    dispatch('change', { value: newValue as any, selectedItems: [] });
  }
</script>

<enhanced-select
  bind:this={selectRef}
  class={className}
  {style}
/>

<style>
  /* Component uses web component styling from @smilodon/core */
</style>
